package nofrills.misc;

import com.google.common.collect.Sets;

import java.util.HashSet;

public class ShardData {

    // shards that come from treasure catches, they can randomly go the inventory instead of hunting box and cannot be trusted
    public static final HashSet<String> fishingShards = Sets.newHashSet(
            "cod",
            "verdant",
            "salmon",
            "piranha",
            "abyssal lanternfish",
            "silentdepth",
            "inferno koi",
            "shinyfish"
    );

    public static final HashSet<String> commonShards = Sets.newHashSet(
            "grove",
            "mist",
            "flash",
            "phanpyre",
            "cod",
            "phanflare",
            "night squid",
            "lapis zombie",
            "hideonleaf",
            "verdant",
            "chill",
            "bogged",
            "voracious spider",
            "hideongift",
            "birries",
            "tank zombie",
            "crow",
            "tadgang",
            "zealot",
            "coralot",
            "harpy",
            "mudworm",
            "golden ghoul",
            "azure",
            "bezal",
            "yog",
            "boreal owl",
            "newt",
            "miner zombie"
    );

    public static final HashSet<String> uncommonShards = Sets.newHashSet(
            "bramble",
            "tide",
            "quake",
            "sparrow",
            "goldfin",
            "troglobyte",
            "hideoncave",
            "salamander",
            "cuboa",
            "pest",
            "mossybit",
            "rain slime",
            "seer",
            "heron",
            "obsidian defender",
            "salmon",
            "viper",
            "praying mantis",
            "zombie soldier",
            "bambuleaf",
            "sycophant",
            "seagull",
            "ent",
            "soul of the alpha",
            "mochibear",
            "magma slug",
            "flaming spider",
            "kiwi",
            "bruiser",
            "stridersurfer",
            "rana",
            "termite"
    );

    public static final HashSet<String> rareShards = Sets.newHashSet(
            "sylvan",
            "cascade",
            "bolt",
            "bambloom",
            "toad",
            "glacite walker",
            "beaconmite",
            "lizard king",
            "python",
            "invisibug",
            "piranha",
            "hideongeon",
            "lapis skeleton",
            "cropeetle",
            "drowned",
            "star sentry",
            "hideondra",
            "abyssal lanternfish",
            "arachne",
            "bitbug",
            "revenant",
            "silentdepth",
            "skeletor",
            "thyst",
            "quartzfang",
            "hideonring",
            "snowfin",
            "kada knight",
            "carrot king",
            "wither specter",
            "matcho",
            "ladybug",
            "lumisquid",
            "crocodile",
            "bullfrog",
            "dreadwing",
            "joydive",
            "stalagmight",
            "fungloom",
            "eel",
            "king cobra",
            "lava flame",
            "draconic",
            "falcon",
            "inferno koi",
            "wither",
            "gecko",
            "hummingbird"
    );

    public static final HashSet<String> epicShards = Sets.newHashSet(
            "terra",
            "cryo",
            "aero",
            "pandarai",
            "leviathan",
            "alligator",
            "fenlord",
            "basilisk",
            "iguana",
            "moray eel",
            "thorn",
            "lunar moth",
            "fire eel",
            "bal",
            "hideonsack",
            "water hydra",
            "flare",
            "loch emperor",
            "prince",
            "komodo dragon",
            "mimic",
            "shellwise",
            "barbarian duke x",
            "toucan",
            "hellwisp",
            "caiman",
            "firefly",
            "sea serpent",
            "ghost",
            "xyz",
            "leatherback",
            "cavernshade",
            "dragonfly"
    );

    public static final HashSet<String> legendaryShards = Sets.newHashSet(
            "tenebris",
            "blizzard",
            "tempest",
            "chameleon",
            "tiamat",
            "wyvern",
            "tortoise",
            "endstone protector",
            "naga",
            "lapis creeper",
            "wartybug",
            "spike",
            "kraken",
            "taurus",
            "daemon",
            "moltenfish",
            "shinyfish",
            "ananke",
            "hideonbox",
            "lord jawbus",
            "burningsoul",
            "cinderbat",
            "megalith",
            "power dragon",
            "condor",
            "sun fish",
            "apex dragon",
            "dodo",
            "jormung",
            "etherdrake",
            "galaxy fish",
            "molthorn",
            "starborn",
            "titanoboa"
    );
}
